default_args1: &args
  ['--testnet',
   'true',
   '--zmq-enabled',
   'true'
  ]


db_synced: &db_synced
  db: https://dbfiles.iota.org/devnet/1.5.0/db-762736.tar
  db_checksum: 50ee1be92056256925263fa62b59128c16ed6fb1a7c34deb872d604956b1abdc
  iri_args: *args
  neighbors: ['tcp://nodeB:15600']

db_behind: &db_behind
  db: https://dbfiles.iota.org/devnet/1.5.0/db-686252.tar
  db_checksum: 735dd385f9b62f562e388306638c2d930049e6070f3decbde4509fd01884e3f6
  iri_args: *args
  neighbors: ['tcp://nodeA:15600']


nodes:
  nodeA: #name
    <<: *db_synced

  nodeB:
    <<: *db_behind



