default_args1: &args
  ['--testnet',
   'true',
   '--zmq-enabled',
   'true'
  ]


db_synced: &db_synced
  db: https://dbfiles.iota.org/devnet/1.5.0/db-536603.tgz
  db_checksum: 0155b92adb8b4d876aa92d1b52c64159770871f813674c398e7a9ea7809b7716
  iri_args: *args
  neighbors: ['tcp://nodeB:15600']

db_behind: &db_behind
  db: https://dbfiles.iota.org/devnet/1.5.0/db-519866.tgz
  db_checksum: 24d23bb91c08384a9ab43de28899dd8d25ea562eae3f02877a43a48691b9b70c
  iri_args: *args
  neighbors: ['tcp://nodeA:15600']


nodes:
  nodeA: #name
    <<: *db_synced

  nodeB:
    <<: *db_behind



