default_args: &args
  ['--testnet-coordinator',
   'EFPNKGPCBXXXLIBYFGIGYBYTFFPIOQVNNVVWTTIYZO9NFREQGVGDQQHUUQ9CLWAEMXVDFSSMOTGAHVIBH',
   '--mwm',
   '1',
   '--milestone-start',
   '0',
   '--testnet-no-coo-validation',
   'true',
   '--testnet',
   'true',
   '--snapshot',
   './snapshot.txt',
   '--zmq-enabled',
   'true'
  ]


db_synced: &db_synced
  db: https://s3.eu-central-1.amazonaws.com/iotaledger-dbfiles/dev/SyncTestSynced.tar.gz
  db_checksum: b1731dff8badf94d820ad37b52a4c906962da31b41e63e2f3d766d6f635029c4
  iri_args: *args

db_behind: &db_to_sync
  db: https://s3.eu-central-1.amazonaws.com/iotaledger-dbfiles/dev/SyncTestLSBehind.tar.gz
  db_checksum: 2063d3b0cc72e317cb0c328bd93a1fe0c2755d620751473bbcdaadd93368f609
  iri_args: *args


nodes:
  nodeA: #name
    <<: *db_synced
    neighbors: ['tcp://nodeB:15600', 'tcp://nodeC:15600', 'tcp://nodeD:15600']

  nodeB:
    <<: *db_synced
    neighbors: ['tcp://nodeA:15600', 'tcp://nodeC:15600', 'tcp://nodeD:15600']

  nodeC:
    <<: *db_synced
    neighbors: ['tcp://nodeA:15600', 'tcp://nodeB:15600', 'tcp://nodeD:15600']

  nodeD:
    <<: *db_to_sync
    neighbors: ['tcp://nodeA:15600', 'tcp://nodeB:15600', 'tcp://nodeC:15600']

